plugins {
    id 'com.android.library'
    id 'kotlin-android'
    id 'maven-publish'
}

android {
    compileSdk 34

    defaultConfig {
        minSdk 21
        targetSdk 34
        versionCode 1
        versionName "1.0.0"
        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    
    kotlinOptions {
        jvmTarget = '1.8'
    }
}

dependencies {
    implementation 'androidx.core:core-ktx:1.12.0'
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'com.squareup.retrofit2:retrofit:2.9.0'
    implementation 'com.squareup.retrofit2:converter-gson:2.9.0'
    implementation 'com.squareup.okhttp3:logging-interceptor:4.12.0'
    implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:1.7.3'
    
    testImplementation 'junit:junit:4.13.2'
    androidTestImplementation 'androidx.test.ext:junit:1.1.5'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.5.1'
}

publishing {
    publications {
        release(MavenPublication) {
            groupId = 'com.navchetna.aegis'
            artifactId = 'aegis-auth-android'
            version = '1.0.0'
            
            pom {
                name = 'Aegis Auth Android SDK'
                description = 'Aegis Auth is a unified identity management system providing secure Android authentication. Consolidation of disparate identity providers into a single canonical source.'
                url = 'https://github.com/navchetnaofficialllp/aegis-auth-sdk-android'
                
                licenses {
                    license {
                        name = 'MIT License'
                        url = 'https://opensource.org/licenses/MIT'
                    }
                }
                
                developers {
                    developer {
                        id = 'navchetna'
                        name = 'Navchetna Technologies'
                        email = 'hello@navchetna.tech'
                    }
                }
                
                scm {
                    connection = 'scm:git:git://github.com/navchetnaofficialllp/aegis-auth-sdk-android.git'
                    developerConnection = 'scm:git:ssh://github.com/navchetnaofficialllp/aegis-auth-sdk-android.git'
                    url = 'https://github.com/navchetnaofficialllp/aegis-auth-sdk-android'
                }
            }
        }
    }
}